### ISSUE TITLE
rbas crud operations on auth.module

### ISSUE THREAD

**Issue by KerimCETINBAS** [stellayazilim/stella.backend#17]
Basic crud operations for roles
- add role,
- update role,
- delete rol
- get role(s)

**Comment by ibrahimsugun** [comment]
AdministratorPerms.AddEnvolopeToUser,    should be  AdministratorPerms.AddEnvolopeToTenant
```ts
export enum AdministratorPerms {
    DeleteRole,
  
    // add
    AddRole,            
    AddEnvolopeToUser,
    UpdateEnvelopeOfUser,  


```
   /*following values missing (etc. 
     UpdateUserRole ,
    RemoveRole */------------------

**Comment by KerimCETINBAS** [comment]
@ibrahimsugun Perms subject of another ticket, feel free to open [new issue ](https://github.com/stellayazilim/stella.backend/issues/new) about it
